---
title: "Oficina Futebol com o R"
#subtitle: ""
institute: "NuPACE"
author: "Caio O. Azevedo"
date: "`r Sys.Date()`"
encoding: "UTF-8"
output:
  xaringan::moon_reader:
    lib_dir: libs
    #chakra: libs/remark-latest.min.js
    css: [xaringan-themer.css]
    nature:
      ratio: 18:10
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: center, middle, animated slideInRight fadeOutLeft, animated slideInRight fadeOutLeft

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
library(magick)
library(fontawesome)

```



```{r xaringan-scribble, echo=FALSE}
xaringanExtra::use_scribble()
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```

```{r xaringan-logo, echo=FALSE}
xaringan_logo <- file.path(
  "https://raw.githubusercontent.com/rstudio/hex-stickers/master",
  "PNG/xaringan.png"
)
xaringanExtra::use_logo(
  image_url = xaringan_logo, 
  position = xaringanExtra::css_position(top = NULL, right = '1em', 
                                         left = NULL, bottom = '1em')
)
```

```{r xaringanExtra-clipboard, echo=FALSE}
xaringanExtra::use_clipboard()

```

```{r xaringan-animate-css, echo=FALSE}
xaringanExtra::use_animate_css(xaringan = FALSE)
```

```{r xaringan-painelset, echo=FALSE}
xaringanExtra::use_panelset()

```
```{r xaringan-extra-styles, echo=FALSE}
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         
  mute_unhighlighted_code = FALSE 
)
```

```{r xaringanExtra, echo = FALSE}
xaringanExtra::use_progress_bar(color = "#261373", location = "top", 
                                height = "10px")
```

Para acessar esse documento:

```{r, echo=FALSE, fig.align='center'}

url <- "https://caio-azevedo.github.io/oficina_futebol"
plot(qrcode::qr_code(url, ecl = 'M'), col = c('white', '#261373'))

```


---
class: center, middle, animated slideInRight fadeOutLeft, animated slideInRight fadeOutLeft

# Introdução

---

# Teste




---


